### ISSUE TITLE
Bad credentials on authenticated requests (recent commits)

### ISSUE THREAD

**Issue by zurfyx** [UdL-EPS-SoftArch/softarch-1617-server#27]
Requests that require credentials do not longer work with the sample user:

Sent headers:

```
Content-Type:application/json
Authorization:Basic dXNlcjpwYXNzd29yZA==
```

**Comment by rogargon** [comment]
Fixed by commit 639fab3548e4d08101024889592d30ca0b33da2c

User admin works again (from inMemory) together with user1 and user2 (from UserRepository)
