### ISSUE TITLE
Logged in user is not taken into account when sending messages

### ISSUE THREAD

**Issue by zurfyx** [UdL-EPS-SoftArch/softarch-1617-server#42]
Being logged in as user1, I can send in send messages as 'user2' by just sending the wrong sender name.

The output is the following:
```
{
  "uri" : "/privateMessages/4",
  "title" : "a",
  "body" : "a",
  "destination" : "user2",
  "sender" : "user1",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/privateMessages/4"
    },
    "privateMessage" : {
      "href" : "http://localhost:8080/privateMessages/4"
    }
  }
}
```

**Comment by Jap9** [comment]
Solved in client, it won't allow sending a message if field sender from the form does not match the logged username
(not pushed yet)

**Comment by zurfyx** [comment]
@Jap9 Use [close #issue](https://help.github.com/articles/closing-issues-via-commit-messages/) in your commit message instead. It will close automatically and will reference the commit which fixed it.
